- op: add
  path: /spec/template/spec/containers/2/args/-
  value: "--enable-capacity"
- op: add
  path: /spec/template/spec/containers/2/env/-
  value:
    name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
- op: add
  path: /spec/template/spec/containers/2/env/-
  value:
    name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
